// <auto-generated />
namespace RaidScheduler.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddingServerSpecificationtoeachplayer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingServerSpecificationtoeachplayer));
        
        string IMigrationMetadata.Id
        {
            get { return "201412140040013_Adding Server Specification to each player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
